export default [
    {
      _id: "M101",
      name: "HTML",
      quizType: "Graded",
      points: "100",
      assignmentGroup: "Quiz",
      shuffle: "Yes",
      timeLimit: "20",
      multipleAttempts: "No",
      sca: "No",
      accesCode: "1111",
      oqat: "No",
      webcam: "No",
      lock: "No",
      dueDate: "Mar 29",
      availableDate: "Mar 28",
      untilDate: "Mar 30",
      course: "RS101", 
      publish: true,
      questions: [{_id: "1", question: "2+2", answers: ["4"],type:"Multiple Choice", correctanswer: "4"},]      
    },
    {
        _id: "M102",
        name: "React",
        quizType: "Graded",
        points: "100",
        assignmentGroup: "Quiz",
        shuffle: "Yes",
        timeLimit: "20",
        multipleAttempts: "No",
        sca: "No",
        accesCode: "1111",
        oqat: "No",
        webcam: "No",
        lock: "No",
        dueDate: "Mar 29",
        availableDate: "Mar 28",
        untilDate: "Mar 30",  
        course: "RS101",
        publish: false, 
        questions: []    
      },
      {
        _id: "M103",
        name: "CSS",
        quizType: "Graded",
        points: "100",
        assignmentGroup: "Quiz",
        shuffle: "Yes",
        timeLimit: "20",
        multipleAttempts: "No",
        sca: "No",
        accesCode: "1111",
        oqat: "No",
        webcam: "No",
        lock: "No",
        dueDate: "Mar 29",
        availableDate: "Mar 28",
        untilDate: "Mar 30",
        course: "RS101",
        publish: false,
        questions: []       
      },
      {
        _id: "M104",
        name: "Axios",
        quizType: "Graded",
        points: "100",
        assignmentGroup: "Quiz",
        shuffle: "Yes",
        timeLimit: "20",
        multipleAttempts: "No",
        sca: "No",
        accesCode: "1111",
        oqat: "No",
        webcam: "No",
        lock: "No",
        dueDate: "Mar 29",
        availableDate: "Mar 28",
        untilDate: "Mar 30",
        course: "RS101",
        publish: false,
        questions: []       
      },
      {
        _id: "M105",
        name: "Bootstrap",
        quizType: "Graded",
        points: "100",
        assignmentGroup: "Quiz",
        shuffle: "Yes",
        timeLimit: "20",
        multipleAttempts: "No",
        sca: "No",
        accesCode: "1111",
        oqat: "No",
        webcam: "No",
        lock: "No",
        dueDate: "Mar 29",
        availableDate: "Mar 28",
        untilDate: "Mar 30",
        course: "RS101",
        publish: false, 
        questions: []       
      },
   
  ];